version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: local-zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
    network_mode: "host"
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: local-kafka
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      KAFKA_CFG_LISTENERS: INTERNAL://127.0.0.1:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://127.0.0.1:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    network_mode: "host"
  ingestor:
    image: ghcr.io/scicatproject/scicat-filewriter-ingest:v4.0 
    container_name: local-ingestor
    volumes:
      - "../configs/config-1.json:/app/config.json"
    network_mode: "host"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

