version: "3"
services:
  sfi-kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: sfi-zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_BROKER_ID: 0
      KAFKA_LOG_RETENTION_MS: -1  # keep data forever, required for tests involving fake "historical" data
      KAFKA_CREATE_TOPICS: "test_data:1:1,test_filewriter_status:1:1,test_filewriter_pool:1:1"
    depends_on:
      - sfi-wait-for-zookeeper
    healthcheck:
      test: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list | grep test_filewriter_pool"
      interval: 30s
      timeout: 10s
      retries: 5

  sfi-zookeeper:
    image: zookeeper:3.6.2

  sfi-wait-for-zookeeper:
    image: dadarek/wait-for-dependencies
    command: sfi-zookeeper:2181
    depends_on:
      - sfi-zookeeper

  sfi-filewriter:
    build:
      context: .
      dockerfile: Dockerfile_sfi_filewriter
    command: /kafka-to-nexus/bin/kafka-to-nexus --command-status-uri kafka:9092/test_filewriter_status --job-pool-uri kafka:9092/test_filewriter_pool --verbosity Debug
    depends_on:
      sfi-kafka:
        condition: service_healthy

  sfi-efu:
    build:
      context: .
      dockerfile: Dockerfile_sfi_efu
      #    image: efu
    environment:
      LD_LIBRARY_PATH: /event-formation-unit/lib
    command: /event-formation-unit/bin/efu -d /event-formation-unit/modules/perfgen --udder -b kafka:9092 --nohwcheck --udder_usleep 100 -t test_data
    depends_on:
      sfi-kafka:
        condition: service_healthy

  sfi-mongodb:
    image: "bitnami/mongodb:latest"

  sfi-scicat-backend:
    #image: scicatproject/backend:latest
    image: dacat/catamel:latest
    depends_on:
      - sfi-mongodb

#  sfi-scicat-ingestor:
#    build:
#      context: .
#      dockerfile: CI/Dockerfile_sfi_scicat_ingestor
#    depends_on:
#      - sfi-scicat-backend
#      - sfi-filewriter
#      - sfi-efu

#  sfi-testing:
#    build:
#      context: .
#      dockerfile: CI/Dockerfile_sfi_scicat_ingestor_testing  
#    depends_on:
#      - sfi-scicat-ingestor

