# Integration test actions

name: Integration

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: string
  workflow_call:
    inputs:
      python-version:
        type: string

jobs:
  tests:
    name: Integration Tests
    runs-on: 'ubuntu-22.04'
    steps:
      - run: sudo apt upgrade --yes
      - run: sudo apt install --yes docker-compose=2.22.0
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: python -m pip install -e .
      - run: docker-compose version
      - run: docker-compose -f tests/docker-compose-file-writer.yml up -d
      - run: python tests/_scicat_ingestor.py -c resources/config.sample.json --verbose
      - run: docker-compose -f tests/docker-compose-file-writer.yml down
